n = input('Digite algo:')
print(type(n))
print('O argumento digitado é do tipo numérico?', n.isnumeric())
print('O argumento digitado é do tipo alfabético?', n.isalpha())
print('O argumento digitado é do tipo alfanumérico?', n.isalnum())
